import { ImmutableQuery } from './query';
import { BaseQueryAccessor } from './accessors';
import { AccessorManager } from './AccessorManager';
import { ESTransport } from './transport';
import { SearchRequest } from './SearchRequest';
import { EventEmitter } from './support';
export interface SearchOptions {
    useHistory?: boolean;
    searchOnLoad?: boolean;
    httpHeaders?: Object;
    basicAuth?: string;
    transport?: ESTransport;
    searchUrlPath?: string;
    timeout?: number;
}
export declare class SearchManager {
    host: string;
    private registrationCompleted;
    completeRegistration: Function;
    state: any;
    translateFunction: Function;
    currentSearchRequest: SearchRequest;
    history: any;
    _unlistenHistory: Function;
    options: SearchOptions;
    transport: ESTransport;
    emitter: EventEmitter;
    resultsEmitter: EventEmitter;
    accessors: AccessorManager;
    queryProcessor: Function;
    query: ImmutableQuery;
    loading: boolean;
    initialLoading: boolean;
    error: any;
    results: any;
    static mock(): SearchManager;
    constructor(host: string, options?: SearchOptions);
    setupListeners(): void;
    addAccessor(accessor: any): any;
    removeAccessor(accessor: any): void;
    addDefaultQuery(fn: Function): any;
    setQueryProcessor(fn: Function): void;
    translate(key: string): any;
    buildQuery(): any;
    resetState(): void;
    addResultsListener(fn: Function): () => Function[];
    unlistenHistory(): void;
    listenToHistory(): void;
    runInitialSearch(): void;
    searchFromUrlQuery(query: any): void;
    performSearch(replaceState?: boolean, notifyState?: boolean): void;
    buildSearchUrl(extraParams?: {}): string;
    reloadSearch(): void;
    search(replaceState?: boolean): void;
    _search(): void;
    setResults(results: any): void;
    compareResults(previousResults: any, results: any): void;
    getHits(): never[];
    getHitsCount(): number;
    getTime(): number;
    getSuggestions(): {};
    getQueryAccessor(): BaseQueryAccessor;
    getAccessorsByType(type: string): any[];
    getAccessorByType(type: string): any;
    hasHits(): boolean;
    hasHitsChanged(): boolean;
    setError(error: any): void;
    onResponseChange(): void;
}
